### PR TITLE
pass planning pipeline from context to solve()

### LINKED ISSUE #169: Planner plugins load every time a driving command is running
### Steps to reproduce
We tried to run a user program based on your API and found out that the reaction time retarded up to 400 ms.

### Expected behavior
All available planner plugins should only loaded once at the beginning of the process.

### Observed behavior
All available planner plugins were loaded every time when a new command started.  

### Logfiles
[rosout.log](https://github.com/PilzDE/pilz_industrial_motion/files/3212914/rosout.log)

### PR DESCRIPTION
**Pull request by jschleicher**
to avoid re-initialization of a new planning pipeline for every request

Fixes #169

### CODE REVIEW

**Comment by jschleicher** [comment]
@rbaur451 Please test the time consumption with this patch applied.

**Comment by rbaur451** [comment]
Without the fix the reaction time is around 210 milliseconds. 
```
[ INFO] [1558592898.235564860]: Combined planning and execution request received for MoveGroupSequenceAction.
[ INFO] [1558592898.235757880]: Planning attempt 1 of at most 1
[ INFO] [1558592898.247100247]: Reading limits from namespace /robot_description_planning
[ INFO] [1558592898.442368916]: Available plugins: pilz::PlanningContextLoaderCIRC pilz::PlanningContextLoaderLIN pilz::PlanningContextLoaderPTP 
[ INFO] [1558592898.442565529]: About to load: pilz::PlanningContextLoaderCIRC
[ INFO] [1558592898.443378805]: Registered Algorithm [CIRC]
[ INFO] [1558592898.443524793]: About to load: pilz::PlanningContextLoaderLIN
[ INFO] [1558592898.444334683]: Registered Algorithm [LIN]
[ INFO] [1558592898.444481818]: About to load: pilz::PlanningContextLoaderPTP
[ INFO] [1558592898.445534258]: Registered Algorithm [PTP]
[ INFO] [1558592898.445698684]: Using planning interface 'Simple Command Planner'
[ INFO] [1558592898.446179410]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1558592898.446391179]: Starting generation of PTP Trajectory!
[ INFO] [1558592898.446587636]: Goal already reached, set one goal point explicitly.
```
With the fix the console output shows that the process only take a few microseconds.
```
[ INFO] [1558956970.864097121]: Combined planning and execution request received for MoveGroupSequenceAction.
[ INFO] [1558956970.864261547]: Planning attempt 1 of at most 1
[ INFO] [1558956970.864469201]: Initialized Point-to-Point Trajectory Generator.
[ INFO] [1558956970.864591649]: Generating PTP trajectory...
```
Thats very fast. I also looked after the time difference between the timestamps of
`sequence_move_group/goal` and `/prbt/gripper_joint_trajectory_controller/follow_joint_trajectory/goal`.
The average difference is around 40 milliseconds. Without the fix it was up to 500 milliseconds.

**Comment by jschleicher** [comment]
@rbaur451 Thank you for confirming of the fix!

**Review by ct2034 — APPROVED** [review]
Tested. Looks considerably faster to me.

**Pull request merged**
