### PR TITLE
Switch active devel branch: kinetic->melodic

### PR DESCRIPTION
**Pull request by martiniil**
Updates ReadMe files

After this change I suppose that we simply open any new PR for melodic-devel. We can keep the old ones and merge one last time from kinetic->melodic after the next release.

### CODE REVIEW

**Review by ct2034 — COMMENTED** [review]
I think we also need to change it in the repo settings. But probably only @dbakovic can do it.

**Comment by jschleicher** [comment]
And you probably want to have a branching model explained: E.g. do a final merge of kinetic into melodic *before merging this PR*. From then on cherry-pick relevant PRs into kinetic on a case-by-case basis ("backport")? Backwards-merge (as stated in the Readme) is not a use-case, I've seen anywhere else...

**Comment by martiniil** [comment]
@jschleicher I would rather do a final kinetic->melodic merge _after_ merging this PR.

@ct2034 Which settings would you change?

**Comment by ct2034** [comment]
You can change it like this (if you have the correct permissions): https://help.github.com/en/articles/setting-the-default-branch

**Comment by martiniil** [comment]
@ct2034 Can we separate the change in the github settings from this PR?

**Comment by martiniil** [comment]
@PilzDE/robotics  Can we merge this and release afterwards?

**Review by hslusarek — APPROVED** [review]

**Pull request merged**
