### PR TITLE
add missing dependency

### PR DESCRIPTION
**Pull request by jschleicher**
necessary for melodic build

### CODE REVIEW

**Comment by jschleicher** [comment]
Please wait for the melodic test build on [travis](https://travis-ci.org/PilzDE/pilz_industrial_motion/jobs/430519174) and then merge here (kinetic-devel is our development branch; merge and release to melodic-devel follows).

**Review by agutenkunst — COMMENTED** [review]
Looks good.

**Review by agutenkunst — APPROVED** [review]
Looks good.

**Comment by jschleicher** [comment]
Hallo Alex,
der PR war noch nicht fertig, deshalb habe ich geschrieben:
Please wait for the melodic test build on travis and then merge here (kinetic-devel is our development branch; merge and release to melodic-devel follows).

I'll follow up with another pr.

Best

Joachim Schleicher
Dipl.-Phys.
Entwicklung Technologien/

Pilz GmbH & Co. KG, Felix-Wankel-Straße 2, 73760 Ostfildern, Deutschland/Germany
Tel.: +49 711 3409-7209, Fax: +49 711 3409 97209
E-Mail: mailto:j.schleicher@pilz.de, Internet: http://www.pilz.com

-----Alexander Gutenkunst <notifications@github.com> schrieb: -----
An: PilzDE/pilz_industrial_motion <pilz_industrial_motion@noreply.github.com>
Von: Alexander Gutenkunst <notifications@github.com>
Datum: 20.09.2018 08:15
Kopie: jschleicher <j.schleicher@pilz.de>, Author <author@noreply.github.com>
Betreff: Re: [PilzDE/pilz_industrial_motion] add missing dependency (#5)

@agutenkunst approved this pull request.
  Looks good.
  —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
Geschäftsführung: Susanne Kunschert, Thomas Pilz
Pilz GmbH & Co. KG, Sitz: Ostfildern, HRA 210 893, Amtsgericht Stuttgart
Kompl. Ges. Peter Pilz GmbH, Sitz: Ostfildern, HRB 210 612, Amtsgericht Stuttgart
Umsatzsteuer: ID-Nr. DE 145 355 773, WEEE-Reg.-Nr. DE 71636849
This email is intended solely for the use of the named address(es). Any unauthorised disclosure, copying or distribution of these confidential information contained therein, or the taking of any action based on it, is prohibited. The sender disclaims any liability for the integrity of this email. Legally binding declarations must be in written form.
Umweltschutz liegt uns am Herzen! - Bitte denken Sie an unsere Umwelt, bevor Sie diese E-Mail drucken.
We do care about the environment! - Please consider the environment before printing this e-mail.

**Pull request merged**
