### PR TITLE
Feature/context guard for robot

### PR DESCRIPTION
**Pull request by hslusarek**
Melodic version of PR #157

### CODE REVIEW

**Comment by hslusarek** [comment]
@rfeistenauer Please have a look. I added a test with a for-loop which shows that the suggested commit does not work.

**Comment by rfeistenauer** [comment]
The problem is not the with statement, but the usage of 'del rob' in previous tests.
The instance is not freed soon enough.
If you use `rob.__del__()` instead, the tests pass.

**Comment by jschleicher** [comment]
@hslusarek @rfeistenauer For future PRs: You can change the target / base branch by pressing "Edit" in the top right...

**Comment by hslusarek** [comment]
@jschleicher Hm... I can only change the title.

**Pull request merged**
