### PR TITLE
WIP: compile using moveit master

### PR DESCRIPTION
**Pull request by jschleicher**
Creates new master branch to build `pilz_trajectory_generation` with upstream moveit:master branch. Development changes are merged in on a regular basis from melodic-devel. Breaking API-changes in moveit:master (targeted for the next ROS release) are thus easily detected on travisCI and fixed by PRs directly to this master branch.

ToDo:
- [ ] Rebase after #216 has been merged.
- [ ] Re-add author emails to travis config
- [ ] Add travis time-based job (running once a day?)

Side Note: The travis configuration uses moveit_ci instead of industrial_ci. Clang is currently not integrated, feel free to also add it.

### CODE REVIEW

**Review by ct2034 — CHANGES_REQUESTED** [review]
There are two separate aspects of this:
* I think it useful to compile with the moveit master branch. I would approve this
* But why do we have to switch to their ci? Is this required for the moveit master to build? This one we need to discuss.

**Comment by jschleicher** [comment]
>     * But why do we have to switch to their ci? Is this required for the moveit master to build? This one we need to discuss.

Yep, I didn't find a documented way to let industrial_ci start from the moveit/moveit:master-source docker image. And the travis timeout will not allow to build the whole moveit repo for every build of our repo first - and it would be waste of ressources...

**Comment by gavanderhoorn** [comment]
> Yep, I didn't find a documented way to let industrial_ci start from the moveit/moveit:master-source docker image.

Doesn't `DOCKER_IMAGE` allow you to do this ([index.rst](https://github.com/ros-industrial/industrial_ci/blob/08cbc8cd6655b345e306dda677fe9df4a42f7284/doc/index.rst), search for `DOCKER_IMAGE`)?

Used [here](https://github.com/swri-robotics/collaborative-robotic-sanding/blob/cb4eecfe1c6b9492823717fb23f256a466907bc4/.travis.yml#L47) fi.

**Comment by ct2034** [comment]
And there are some things to note: https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#use-custom-docker-images

**Comment by jschleicher** [comment]
> Doesn't `DOCKER_IMAGE` allow you to do this ([index.rst](https://github.com/ros-industrial/industrial_ci/blob/08cbc8cd6655b345e306dda677fe9df4a42f7284/doc/index.rst), search for `DOCKER_IMAGE`)?

Just specifying the image does not overlay the pre-built workspace (see [travis job](https://travis-ci.org/PilzDE/pilz_industrial_motion/builds/595983124?utm_source=github_status&utm_medium=notification)) and how could I specify a `ROS_UNDERLAY` (CATKIN_CONFIG deprecated, see [travis](https://travis-ci.org/PilzDE/pilz_industrial_motion/builds/595995762?utm_source=github_status&utm_medium=notification))?

Feel free to investigate further - for me it looks simpler to switch to moveit_ci - as we are building a moveit-plugin anyways.

**Comment by gavanderhoorn** [comment]
I specifically commented on:

> I didn't find a documented way to let industrial_ci start from the moveit/moveit:master-source docker image

As this repository is going to go away anyway then it becomes a moot point of course.

**Pull request closed without merging**
