### PR TITLE
enable roslint_python

### PR DESCRIPTION
**Pull request by jschleicher**
for better python readability.
Add test dependency to check it with CI job in the future.
Fixed PEP issues with the help of pycharm.

### CODE REVIEW

**Comment by jschleicher** [comment]
rebased onto current melodic-devel.

**Comment by jschleicher** [comment]
@hslusarek @martiniil @agutenkunst @ct2034 any interest in using standard PEP-8 python style?
I don't want to solve conflicts / rebase again...

**Comment by agutenkunst** [comment]
Sorry just stumbled upon this now. Could you rebase one more time :flushed:

**Comment by jschleicher** [comment]
Is there a consensus in the team, that you want this? You'd need to commit yourself to follow PEP-8 in the future... Please Review now / let me know your comments.

If yes, I'll prepare the PR for merging (rebase or similar) and incorporate comments at the same time.

**Review by ct2034 — APPROVED** [review]
I think this is a good idea.
@jschleicher Is roslint_python using pep8 style?

**Comment by jschleicher** [comment]
@ct2034 Yes. See http://wiki.ros.org/roslint#Reference

**Comment by ct2034** [comment]
Also, @martiniil and @agutenkunst are fine with this -> merging.

**Pull request merged**
