### PR TITLE
Ensure valid circ aux point if possible

### PR DESCRIPTION
**Pull request by martiniil**
KDL::Path_Circle computes a plane from start, center and auxiliary point.
So the interim point is not suited, if start, center and interim are colinear.

- [x] check that using goal as aux point is valid
- [x] implement test reproducing this issue

### CODE REVIEW

**Comment by hslusarek** [comment]
@agutenkunst Please have a look at this merge request. You also done a lot of work with regard to the circ command. Please check if you have done something similar... Please be also aware of the fact that this merge request, will merge into kinetic and not melodic.

**Review by ct2034 — CHANGES_REQUESTED** [review]
Command is executed succefully but ends up at wrong point. See https://github.com/ct2034/my_pilz_sandbox/blob/f69e6fa81c501d852623f4a3215bef6150ad5261/my_pilz_sandbox/scripts/circ.py

**Comment by martiniil** [comment]
Actually, there was a bug in testutils (see #125) preventing the circ test from failing.

**Review by ct2034 — APPROVED** [review]

**Comment by ct2034** [comment]
succesfully tested with https://github.com/ct2034/my_pilz_sandbox/blob/f481afe227351fa657c69c789c8149cbaa83cf50/my_pilz_sandbox/scripts/circ.py

**Pull request merged**
